spring.application.name=robot-control-system
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/robot_control
spring.datasource.username=robot_be
spring.datasource.password=robot123
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# JWT Configuration
app.jwt.secret=dGhpc2lzYXZlcnlzZWN1cmVzZWNyZXRrZXlmb3Jqd3R0b2tlbmdlbmVyYXRpb24xMjM0NTY3ODkw
app.jwt.expiration-ms=86400000
app.jwt.refresh-expiration-ms=604800000

# DataStax Astra DB
spring.cassandra.keyspace-name=robot_telemetry
spring.cassandra.scb-filename=${SCB_PATH:secure-connect-robot-control-log.zip}
spring.cassandra.username=token
spring.cassandra.password=${ASTRA_TOKEN:AstraCS:HLvaNDYXUNfFpTGmXXJSTErn:6910c37087bb76c1a5617b73fa9667876b6ec880ff2cb4ca1ca341e38f929238}
spring.cassandra.schema-action=NONE



