spring.application.name=robot-control-system
server:
port: 8080

spring:
datasource:
spring.datasource.url=jdbc:postgresql://localhost:5432/robot_control
spring.datasource.username=robot_be
spring.datasource.password=robot123
jpa:
hibernate:
ddl-auto: none


spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# JWT Configuration
app.jwt.secret=dGhpc2lzYXZlcnlzZWN1cmVzZWNyZXRrZXlmb3Jqd3R0b2tlbmdlbmVyYXRpb24xMjM0NTY3ODkw
app.jwt.expiration-ms=86400000
app.jwt.refresh-expiration-ms=604800000

